version: "3"
services:
  app:
    container_name: app_yggdrasil
    restart: always
    build: .
    links:
      - mongo
    volumes:
      - .:/home/app/
      - /home/app/node_modules  
    ports:
      - "3001:3000"
  mongo:
    container_name: mongo_yggdrasil
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata: